"""
Game constants to replace magic numbers throughout the codebase.
"""

# UI and rendering constants
MENU_TILE_SIZE = 48
UI_STATS_SURFACE_WIDTH = 340
UI_STATS_SURFACE_HEIGHT = 200
UI_STAT_LINE_HEIGHT = 15
UI_MENU_PADDING = 15
UI_MENU_LINE_SPACING = 20

# Parallax background constants
PARALLAX_BACKGROUND_WIDTH = 2048
PARALLAX_BACKGROUND_RESET_THRESHOLD = 2047

# Time and animation constants
SPLASH_SCREEN_FADE_IN_TIME = 0.5
SPLASH_SCREEN_DISPLAY_TIME = 1.5
SPLASH_SCREEN_FADE_OUT_START = 4.5
SPLASH_SCREEN_FADE_OUT_END = 5.5
SPLASH_SCREEN_TOTAL_TIME = 6.0

# Player and world constants
SURFACE_LIGHT_LEVEL_Y = 110
MAX_DELTA_TIME = 0.033333  # 30 FPS minimum
ALPHA_MAX = 255

# Lighting constants
LIGHT_REDUCTION_PER_FRAME = 16
GLOBAL_LIGHTING = 255
SKY_DARKEN_FACTOR_START_Y = 55
SKY_DARKEN_FACTOR_RANGE_Y = 110
SKY_DARKEN_MAX_FACTOR = 0.7

# Item drop constants
DEFAULT_ITEM_DROP_RATE = 25

# Camera movement constants
CAMERA_SMOOTH_FACTOR = 4
CAMERA_MOMENTUM_FACTOR = 8
MAX_CAMERA_SPEED_MULTIPLIER = 200

# World snapshot constants
WORLD_SNAPSHOT_TILE_SCALE = 2

# Menu selection constants
MENU_SCROLL_VELOCITY_MULTIPLIER = 3
MENU_SCROLL_DAMPENING = 0.9
CRAFT_MENU_SCROLL_VELOCITY = 200

# Color constants for UI feedback
UI_GOOD_COLOR_RGB = (10, 230, 10)
UI_BAD_COLOR_RGB = (230, 10, 10)
WHITE_COLOR_RGB = (255, 255, 255)

# Time calculation constants
PLAYTIME_CALCULATION_FACTOR = 0.4
PLAYTIME_MULTIPLIER = 6
TIME_SMOOTH_FACTOR = 0.75
TIME_BASE_FACTOR = 0.25

# Physics constants  
ITEM_THROW_VELOCITY_X = 32
ITEM_THROW_VELOCITY_Y_RANGE = 2

# Menu positioning constants
SAVE_SELECT_SURFACE_WIDTH = 315
SAVE_SELECT_SURFACE_HEIGHT = 360
MENU_SURFACE_WIDTH_MULTIPLIER = 336
MENU_SURFACE_WIDTH_OFFSET = 315

# Thread timing constants
DEFAULT_THREAD_TIME = 0.2

# Inventory and UI constants
HOTBAR_SIZE = 10
INVENTORY_ROWS = 4
INVENTORY_COLS = 10
CHEST_INVENTORY_ROWS = 2

# Menu scroll limits
MENU_ITEM_HEIGHT = 62
MENU_VISIBLE_ITEMS = 5
MENU_ITEM_TOTAL_HEIGHT = 61

# Background scroll constants
BACKGROUND_SCROLL_SPEED = 10
BACKGROUND_PARALLAX_SPEED = 0.001
MENU_BACKGROUND_PARALLAX_SPEED = 0.2

# FPS display update frequency
FPS_UPDATE_FREQUENCY = 0.5

# Animation and particle constants
PARTICLE_COUNT_RESPAWN = 20
PARTICLE_COUNT_RESPAWN_ARRIVE = 40
PARTICLE_MAGNITUDE_BASE = 1
PARTICLE_MAGNITUDE_RANGE = 6
PARTICLE_SIZE = 15

# Sound volume adjustment step
SOUND_VOLUME_STEP = 0.05

# Menu text input limits
PLAYER_NAME_MAX_LENGTH = 15
WORLD_NAME_MAX_LENGTH = 27